language: cpp
dist: trusty
cache: pip
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
            - python3-pip

before_script:
        - pip3 install --user future pymavlink
        - CXX="g++-6"
        - CC="gcc-6"

script:
        - ./autogen.sh c --with-systemdsystemunitdir=/usr/lib/systemd/system
        - make -j
        - make check PYTHON=python3
